services:

  network-deploy-service:
    networks:
      - ms_net

  ####################################################################################################
  #  base configuration for all microservices
  ####################################################################################################
  ms-base-config:
    extends:
      service: network-deploy-service
    mem_limit: 700m

  ####################################################################################################
  # common configuration for services which depends on config-server and eureka-server
  ####################################################################################################
  ms-configserver-config:
    extends:
      service: ms-base-config

    depends_on:
      config-server:
        condition: service_healthy

    environment:
      - SPRING_PROFILES_ACTIVE=stage
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071

  ####################################################################################################
  # common configuration for services which depends on config-server and eureka-server
  ####################################################################################################
  ms-eurekaserver-config:
    extends:
      service: ms-configserver-config

    depends_on:
      eureka-server:
        condition: service_healthy

    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8070/eureka


  ####################################################################################################
  # common configuration for services which depends on config-server and eureka-server
  ####################################################################################################
  ms-all-config:
    extends:
      service: ms-eurekaserver-config

    depends_on:
      account-service:
        condition: service_healthy
      card-service:
        condition: service_healthy
      loan-service:
        condition: service_healthy

