server:
  port: 8083

spring:

  application:
    name: loan-service

  profiles:
    active: dev

  config:
    import: "optional:configserver:http://localhost:8071/"

  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        multiplier: 2

  datasource:
    url: jdbc:mysql://mysql_ls:3306/loan_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
