server:
  port: 8083

spring:

  application:
    name: loan-service

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  ##################################################
  # JPA Properties
  ##################################################
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


##################################################
# Actuator Properties
##################################################
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true

    # used for graceful shutdown using : http://{{service-name}}/actuator/shutdown
    shutdown:
      access: unrestricted

  # actuator/health : http://{{service-name}}/actuator/health
  health:
    ping:
      enabled: true
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  # enable ifo for actuator/info
  info:
    env:
      enabled: true

# actuator/info : http://{{service-name}}/actuator/info
info:
  app:
    name: "loans"
    description: "Loans application"

# enabling logging for Debug
logging:
  level:
    com:
      ms:
        loan: DEBUG
