eureka:
  instance:
    hostname: localhost

    # Indicates the frequency the client sends heartbeats to server to indicate that it is still alive
    lease-renewal-interval-in-seconds: 30

    #Indicates the duration the server waits since it received the last heartbeat before it can evict an instance
    lease-expiration-duration-in-seconds: 90

  client:
    # Eureka server don't need registry of other microservices
    fetch-registry: false
    # Don't register with itself
    register-with-eureka: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    # By default, self-preservation mode is enabled but if you need to disable it you can change it to 'false'
    enable-self-preservation: true

    # A scheduler(EvictionTask) is run at this frequency which will evict instances from the registry if the lease of the instances are
    # expired as configured by lease-expiration-duration-in-seconds. It will also check whether the system has reached self-preservation
    # mode (by comparing actual and expected heartbeats) before evicting.
    eviction-interval-timer-in-ms: 60000

    #This value is used to calculate the expected % of heartbeats per minute eureka is expecting.
    renewal-percent-threshold: 0.85

    #A scheduler is run at this frequency which calculates the expected heartbeats per minute
    renewal-threshold-update-interval-ms: 900000
